<?
// all pages
$l['Logout'] = "Déconnexion";
$l['Log_in'] = "Connexion";
$l['Administration'] = "Administration";    
$l['signup'] = "S’inscrire";
$l['register'] = "S’enregistrer";        
$l['forgot'] = "Mot de passe oublié ?";
$l['hello'] = "Bonjour";
$l['newListings'] = "Nouvelles inscriptions";
$l['SearchField'] = "Recherche";
$l['advancedSearchLink'] = "Recherche avancée";
$l['Please'] = "S’il vous plaît";
$l['Copyright'] = "Droit d’auteur";
$l['AllRights'] = "Tous droits réservés";
$l['Save'] = "Sauvegarder";	
// home
$l['latestItems'] = "Derniers articles";
// classifieds
$l['Free'] = "Gratuit";
$l['Bestoffer'] = "Meilleur offre";
$l['Photo'] = "Photo";
$l['Title'] = "Titre";
$l['Price'] = "Prix";
$l['Date'] = "Date"; 
$l['noads'] = "La catégorie ne contient aucune annonce. Choisit une catégorie différente ou une sous-catégorie dans le menu à gauche.";
$l['Myadsnone'] = "Vous n’avez aucune annonce.";
$l['PleaseAdd'] = "Poster une nouvelle annonce classée";
$l['Photos'] = "Photos";
$l['Video'] = "Vidéo";
$l['Map'] = "Plan";
$l['Addedby'] = "Ajouté par";
$l['sendPrivateMessage'] = "Send private message";
$l['Adddate'] = "Ajouter une date";
$l['Details'] = "Détails";
$l['ChooseTitle'] = "Enter a title";
$l['ChooseCategory'] = "Choisissez une catégorie";
$l['choose_sub_category'] = "Choisissez une sous-catégorie";		
$l['Description'] = "Description";
$l['Location'] = "Lieu";
$l['optional'] = "Facultatif";
$l['Max2mb'] = "max 2Mb pour chaque fichier";
$l['VideoCode'] = "Code HTML de Youtube ou un autre site de partage de vidéo";
$l['SearchResults'] = "Annonces classées pour";	
$l['ContactSeller'] = "Contacter le vendeur";	
$l['AdStatus'] = "Etat";
$l['Views'] = "Views";
$l['Approved'] = "Approuvé";
$l['Waiting'] = "En attente";
$l['Payment'] = "Paiement";
$l['Upgrade'] = "Mise à niveau"; 
$l['AreYouSure'] = "Etes-vous sûre ?"; 	   
$l['Actions'] = "Actions";
$l['ShareSocial'] = "Partager";	
$l['Choosepayment'] = "Choisissez votre type de mise à niveau";
$l['Topcategory'] = "En vedette – Annonces montrer en haut de la page de la catégorie avant les annonce non vedette.";
$l['BoldAd'] = "Gras – Le titre de l’annonces et le prix seront en Gras pour les faire ressortir.";
$l['paypalPay'] = "Payez avec PayPal";
$l['PaymentThanks'] = "Merci pour votre paiement";
$l['PaymentIncomplete'] = "Votre paiement n’est pas complet";
$l['urlText']   = "URL 'name'";
$l['urlTextEx'] = "(ex. Click here for more information)";
$l['urlLink']   = "URL";
$l['urlLinkEx'] = "(ex. http://www.domain-name.com/link-to-go-to)";
// search
$l['Advancedsearch'] = "Recherche avancée";
$l['From'] = "à partir de";
$l['USAstate'] = "Etat ou Région";
$l['Search'] = "Recherche";
// Main menu
$l['home'] = "Accueil";
$l['contact'] = "Contacter";
$l['postAd'] = "Poster une annonce";
$l['sign_up'] = "S’inscrire";
$l['profile'] = "Profil";
$l['myAds'] = "Mes annonces";
$l['messages'] = "Messages";
$l['newmessages'] = "New Messages";
$l['help'] = "Aide";
$l['news'] = "Nouvelles";
$l['articles'] = "Articles";
// log in
$l['Incorrect_login_or_password'] = "Identifiant ou mot de passe incorrectes ";
$l['Login'] = "Identifiant";
$l['Password'] = "Mot de passe";
$l['Name'] = "Prénom";
$l['YourName'] = "Votre nom";
$l['Last_name'] = "Nom";
$l['Password'] = "Mot de passe";
$l['Confirm_password'] = "confirmer le mot de passe";
$l['Country'] = "Pays";
$l['City'] = "Ville";
$l['Submit'] = "Soumettre";
$l['RegComplete'] = "Enregistrement terminé vous pouvez maintenant";
$l['RegCompletePostAd'] = "Poster une annonce classée";
$l['Region'] = "Région";
$l['state'] = "Etat";
$l['Area'] = "Région";
$l['FullAdress'] = "Adresse complète";
$l['streetAddress'] = "Adresse de la rue";
$l['Street'] = "Rue";
$l['HouseNum'] = "Numéro de maison";
$l['Zip'] = "Code postale";
$l['Address'] = "Adresse";
$l['URL'] = "URL (site web)";
$l['Fax'] = "Fax";
$l['Mob'] = "Téléphone mobile";
$l['phone'] = "Téléphone";
$l['mob'] = "Téléphone mobile";
$l['Profile'] = "Profil";
$l['EditProfile'] = "Modifier le profil";
$l['PassNotEqual'] = "Les mots de passe ne sont pas identiques";
$l['LoginNic'] = "Identifiant (Pour identifiant et sera montrer dans les annonces)";
$l['SubmitReg'] = "S’inscrire";
//profile
$l['Delete'] = "Supprimer";
$l['Edit'] = "Modifier";
$l['AreYouSure'] = "Etes-vous sûre?";
$l['Profile'] = "Profil";
$l['IncorrOldPass'] = "L’ancien mot de passe n’est pas valide";
$l['PassnotEq'] = "Les mots de passe ne sont pas identiques";
$l['oldpass'] = "Ancien mot de passe";
$l['newpass'] = "Nouveau mot de passe";
$l['Back'] = "Retour";
$l['Pages'] = "Pages";
$l['AllRFields'] = "Tous les champs sont requis";
$l['ReqEmail'] = "Entrez votre e-mail";
$l['EmailInc'] = "E-mail incorrect";
$l['EmailNotFound'] = "E-mail non trouvé";
$l['ForgotEmailBody'] = "Notre nouveau mot de passe %pass%";
$l['ForPassword'] = "Récupération du mot de passe";
$l['NewPassSent'] = "Un nouveau mot de passe a été envoyer dans votre e-mail";
// profile
$l['Inbox'] = "Boite de Réception";
$l['Outbox'] = "Boite d’émission";
$l['Compose'] = "Composer";
$l['Reply'] = "Répondre";
$l['DeleteMess'] = "Supprimer";
$l['MarkedMessages'] = " Avec messages sélectionnés ";
$l['MasrkAsRead'] = "Marquer comme lu";
$l['MEssageSecSend'] = "Message envoyer avec succès";
$l['UserNotFound'] = "Utilisateur non trouvé";
$l['ForUser'] = "à";
$l['EnterLogin'] = "Entrer l’identifiant de l’utilisateur";
$l['IncorrectLoginOrPass'] = "Identifiant ou mot de passe incorrects";
$l['UserNotFound'] = " Utilisateur non trouvé ";
$l['PassNotEqual'] = "Mots de passe ne sont pas identiques";
$l['BothPassReq'] = "Entrez le nouveau et l’ancien mot de passe";
$l['IncOldPass'] = "Ancien mot de passe incorrect";
$l['ShowOnly'] = "Montrer seulement les annonces de ma ville";
//PostAd
$l['toPostad'] = "Pour poster une annonce.";	
$l['Video'] = "Vidéo";
$l['VideoCode'] = "Entrer le code intégré de la vidéo";
$l['optional'] = "Facultatif";
$l['delete'] = "Supprimer";
$l['images_extensions'] = "Images: (.jpg, .png, .gif - max 2Mb pour chaque fichier)";
$l['photos_videos'] = "Photos and Vidéos:";
$l['zip_postal_code'] = "Code Postale(Facultatif)";
$l['or'] = "Ou";
$l['city'] = "Ville";
$l['optional'] = "Facultatif";
$l['us_state'] = "Etat ou Région";
$l['country'] = "Pays";
$l['location'] = "Lieu";
$l['free'] = "Gratuit";
$l['best_offer'] = "Meilleur offre";
$l['wanted'] = "Wanted";
$l['description'] = "Description";
$l['title'] = "Titre";
$l['choose_category'] = "Choisissez une catégorie";
$l['Price_classified'] = "Prix";
$l['Details'] = "Détails";
$l['emailAddress'] = "E-mail";
$l['footerLink'] = "Logiciel des annonces classées";
// contacts
$l['ContactName'] = "Votre Nom";
$l['ContactEmail'] = "Votre adresse e-mail";
$l['subject'] = "Sujet";
$l['message'] = "Message";
$l['SendMessage'] = "envoyer un Message";
$l['succSent'] = "Votre message a été envoyer";
$l['captcha_error'] = "S’il vous plaît enter la captcha correcte ";
//Language variable for Email
$e['contact_seller'] = "Contacter le vendeur";
$e['message_sent'] = "Votre message a été envoyer au vendeur";
$e['invalid_captcha'] = "S’il vous plaît entrer une captcha valide";
$e['firstNameLastName'] = "Prénom et Nom";
$e['emailAddress'] = "Email";
$e['emailMessage'] = "Message";
$e['emailURL'] = "URL";
$e['approvalMailsubject'] = "Une nouvelle annonce a été poster. Voila les détails de l’annonce ";
$e['approvalMailTitle'] = "Titre";
$e['approvalMailDescription'] = "Description";
$e['approvalMailName'] = "Nom";
$e['approvalMailPhone'] = "Téléphone";
$e['approvalLink'] = "Voila le lien d’acceptation: (S’il vous plaît veuillez d’abord vous connectez dans l’administration) ";
$e['adEditedapprovalMailsubject'] = "Une annonces a été modifier. Voila les détails de l’annonce ";

//News and Articles
$l['moreInfo'] = "more info >";

// Added to make URLs without odd characters of certain languages
foreach($l AS $key=>$value)
{
$l[$key] = htmlentities($value); 
}
?>