<?
// all pages
$l['Logout'] = "Logout";
$l['Log_in'] = "Login";
$l['Administration'] = "Amministrazione";    
$l['signup'] = "Registrazione";
$l['register'] = "registrati";        
$l['forgot'] = "Password dimenticata?";
$l['hello'] = "ciao";
$l['newListings'] = "Nuovi elenchi";
$l['SearchField'] = "Cerca...";
$l['advancedSearchLink'] = "Ricerca Avanzata";
$l['Please'] = "Per favore";
$l['Copyright'] = "Copyright";
$l['AllRights'] = "Tutti i diritti riservati.";
$l['Save'] = "Salva";	
// home
$l['latestItems'] = "Ultimi Oggetti";
// classifieds
$l['Free'] = "Gratis";
$l['Bestoffer'] = "Miglior offerta";
$l['Photo'] = "Foto";
$l['Title'] = "Titolo";
$l['Price'] = "Prezzo";
$l['Date'] = "Data";
$l['noads'] = "La categoria non contiene annunci. Scegli una diversa categoria o sottocategoria nel menu a sinistra.";
$l['Myadsnone'] = "Non hai annunci.";
$l['PleaseAdd'] = "Pubblica un nuovo annuncio classificato";
$l['Photos'] = "Foto";
$l['Video'] = "Video";
$l['Map'] = "Mappa";
$l['Addedby'] = "Aggiunto da";
$l['sendPrivateMessage'] = "Send private message";
$l['Adddate'] = "Aggiungi data";
$l['Details'] = "Dettagli";
$l['ChooseCategory'] = "Scegli una categoria";
$l['choose_sub_category'] = "Scegli una sottocategoria";	
$l['Description'] = "Descrizione";
$l['Location'] = "Luogo";
$l['optional'] = "opzionale";
$l['Max2mb'] = "massimo 2Mb per ogni file";
$l['VideoCode'] = "codice HTML da YouTube o da un altro sito di condivisione video";
$l['SearchResults'] = "Annuncio classificato per";	
$l['ContactSeller'] = "Contatta Venditore";	
$l['AdStatus'] = "Stato";
$l['Views'] = "Visite";
$l['Approved'] = "Approvato";
$l['Waiting'] = "In attesa";
$l['Payment'] = "Pagamento";
$l['Upgrade'] = "Upgrade"; 
$l['AreYouSure'] = "Sei sicuro?"; 	   
$l['Actions'] = "Azioni";
$l['ShareSocial'] = "Condividi";	
$l['Choosepayment'] = "Seleziona il tuo tipo di upgrade";
$l['Topcategory'] = "In Rilievo - Annuncio mostrato in cima alla pagina di categoria prima degli annunci non in rilievo.";
$l['BoldAd'] = "In Grassetto - Il titolo e il prezzo dell'annuncio saranno in grassetto facendolo risaltare.";
$l['paypalPay'] = "Paga con PayPal";
$l['PaymentThanks'] = "Grazie per il tuo pagamento.";
$l['PaymentIncomplete'] = "Il tuo pagamento è incompleto.";
$l['urlText']   = "URL 'name'";
$l['urlTextEx'] = "(ex. Click here for more information)";
$l['urlLink']   = "URL";
$l['urlLinkEx'] = "(ex. http://www.domain-name.com/link-to-go-to)";
// search
$l['Advancedsearch'] = "Ricerca avanzata";
$l['From'] = "Da";
$l['USAstate'] = "Stato o Regione";
$l['Search'] = "Cerca";
// Main menu
$l['home'] = "Home";
$l['contact'] = "Contatti";
$l['postAd'] = "Pubblica annuncio";
$l['sign_up'] = "Registrazione";
$l['profile'] = "Profilo";
$l['myAds'] = "I miei annunci";
$l['messages'] = "Messages";
$l['newmessages'] = "New Messages";
$l['help'] = "Aiuto";
$l['news'] = "Novità";
$l['articles'] = "Articoli";
// log in
$l['Incorrect_login_or_password'] = "Login or password errati";
$l['Login'] = "Login";
$l['Password'] = "Password";
$l['Name'] = "Nome";
$l['YourName'] = "Il tuo Name";
$l['Last_name'] = "Cognome";
$l['Password'] = "Password";
$l['Confirm_password'] = "Conferma password";
$l['Country'] = "Nazione";
$l['City'] = "Città";
$l['Submit'] = "Invia";
$l['RegComplete'] = "Registrazione completata, ora puoi";
$l['RegCompletePostAd'] = "pubblica un annuncio classificato.";
$l['Region'] = "Regione";
$l['state'] = "Stato";
$l['Area'] = "Regione";
$l['FullAdress'] = "Indirizzo completo";
$l['streetAddress'] = "Indirizzo";
$l['Street'] = "Via";
$l['HouseNum'] = "Numero civico";
$l['Zip'] = "Zip / Codice postale";
$l['Address'] = "Indirizzo";
$l['URL'] = "URL (sito)";
$l['Fax'] = "Fax";
$l['Mob'] = "Cellulare";
$l['phone'] = "Telefono";
$l['mob'] = "Cellulare";
$l['Profile'] = "Profilo";
$l['EditProfile'] = "Modifica profilo";
$l['PassNotEqual'] = "Le password non sono uguali";
$l['LoginNic'] = "Login (per loggarti ed essere mostrato negli annunci)";
$l['SubmitReg'] = "Registrazione";
//profile
$l['Delete'] = "Cancella";
$l['Edit'] = "Modifica";
$l['AreYouSure'] = "Sei sicuro?";
$l['Profile'] = "Profilo";
$l['IncorrOldPass'] = "La vecchia password non è valida";
$l['PassnotEq'] = "Le password non sono uguali";
$l['oldpass'] = "Vecchia password";
$l['newpass'] = "Nuova password";
$l['Back'] = "Indietro";
$l['Pages'] = "Pagine";
$l['AllRFields'] = "Tutti i campi sono obbligatori";
$l['ReqEmail'] = "Inserisci la tua e-mail";
$l['EmailInc'] = "E-mail sbagliata";
$l['EmailNotFound'] = "E-mail non trovata";
$l['ForgotEmailBody'] = "La tua nuova password è %pass%";
$l['ForPassword'] = "Recupero password";
$l['NewPassSent'] = "Una nuova password è stata mandata alla tua e-mail";
// profile
$l['Inbox'] = "Inbox";
$l['Outbox'] = "Outbox";
$l['Compose'] = "Componi";
$l['Reply'] = "Rispondi";
$l['DeleteMess'] = "Cancella";
$l['MarkedMessages'] = "Con i messaggi selezionati";
$l['MasrkAsRead'] = "Segna come letto";
$l['MEssageSecSend'] = "Il messaggio è stato inviato con successo";
$l['UserNotFound'] = "Utente non trovato";
$l['ForUser'] = "a";
$l['EnterLogin'] = "Inserisci la tua login";
$l['IncorrectLoginOrPass'] = "Login or password sbagliati";
$l['UserNotFound'] = "Utente non trovato";
$l['PassNotEqual'] = "Le password non sono uguali";
$l['BothPassReq'] = "Inserisci vecchia e nuova password";
$l['IncOldPass'] = "La vecchia password è sbagliata";
$l['ShowOnly'] = "Mostra solo annunci dalla mia città";
//PostAd
$l['toPostad'] = "per postare un annuncio.";	
$l['Video'] = "Video";
$l['VideoCode'] = "Inserisci qui il codice per integrare il video.";
$l['optional'] = "Opzionale";
$l['delete'] = "cancella";
$l['images_extensions'] = "Immagini: (.jpg, .png, .gif - massimo 2Mb per ogni file)";
$l['photos_videos'] = "Foto e Video:";
$l['zip_postal_code'] = "Zip / Codice postale (opzionale)";
$l['or'] = "o";
$l['city'] = "Città";
$l['optional'] = "opzionale";
$l['us_state'] = "Stato o Regione";
$l['country'] = "Nazione";
$l['location'] = "Luogo";
$l['free'] = "gratis";
$l['best_offer'] = "Miglior offerta";
$l['wanted'] = "Wanted";
$l['description'] = "Descrizione";
$l['title'] = "Titolo";
$l['choose_category'] = "Scegli Categoria";
$l['Price_classified'] = "Prezzo";
$l['Details'] = "Dettagli";
$l['emailAddress'] = "Email";
$l['footerLink'] = "Software per Annunci Classificati";
// contacts
$l['ContactName'] = "Il tuo nome";
$l['ContactEmail'] = "Il tuo indirizzo email";
$l['subject'] = "Oggetto";
$l['message'] = "Messaggio";
$l['SendMessage'] = "Invia Messaggio";
$l['succSent'] = "Il tuo messaggio è stato inviato";
$l['captcha_error'] = "Inserisci il captcha corretto";
//Language variable for Email
$e['contact_seller'] = "Contatto del Venditore";
$e['message_sent'] = "Il tuo Messaggio è stato Inviato al Venditore";
$e['invalid_captcha'] = "Inserisci un captcha valido";
$e['firstNameLastName'] = "Nome e cognome";
$e['emailAddress'] = "Email";
$e['emailMessage'] = "Messaggio";
$e['emailURL'] = "URL";
$e['approvalMailsubject'] = "È stato postato un nuovo annuncio. Ecco i dettagli dell'annuncio.";
$e['approvalMailTitle'] = "Titolo";
$e['approvalMailDescription'] = "Descrizione";
$e['approvalMailName'] = "Nome";
$e['approvalMailPhone'] = "Telefono";
$e['approvalLink'] = "Ecco il link di approvazione: (per favore, loggati come admin prima) ";
$e['adEditedapprovalMailsubject'] = "Un Annuncio è stato modificato. Ecco i dettagli dell'annuncio.";

//News and Articles
$l['moreInfo'] = "more info >";

// Added to make URLs without odd characters of certain languages
foreach($l AS $key=>$value)
{
$l[$key] = htmlentities($value); 
}
?>