<?
// all pages
$l['Logout'] = "Salir";
$l['Log_in'] = "Accesar";
$l['Administration'] = "Administración";    
$l['signup'] = "Inscribirse";
$l['register'] = "Registrarse";        
$l['forgot'] = "¿Olvidaste tu contraseña?";
$l['hello'] = "Hola";
$l['newListings'] = "Nuevos listados";
$l['SearchField'] = "Buscar...";
$l['advancedSearchLink'] = "Busqueda Avanzada";
$l['Please'] = "Porfavor";
$l['Copyright'] = "Derechos de Autor";
$l['AllRights'] = "Derechos Reservados.";
$l['Save'] = "Guardar";	
// home
$l['latestItems'] = "Los Ultimos Artículos";
// classifieds
$l['Free'] = "Gratis";
$l['Bestoffer'] = "Mejor Oferta";
$l['Photo'] = "Foto";
$l['Title'] = "Titulo";
$l['Price'] = "Precio";
$l['Date'] = "Fecha";
$l['noads'] = "Esta Categoria no contiene anuncios, eliga una categoria o subcategoria diferente en el menu de la izquierda.";
$l['Myadsnone'] = "Usted no tiene anuncios.";
$l['PleaseAdd'] = "Sube un nuevo anuncio clasificado";
$l['Photos'] = "Fotos";
$l['Video'] = "Video";
$l['Map'] = "Mapa";
$l['Addedby'] = "Agregado por";
$l['sendPrivateMessage'] = "Send private message";
$l['Adddate'] = "Fecha de Subida";
$l['Details'] = "Detalles";
$l['ChooseTitle'] = "Enter a title";
$l['ChooseCategory'] = "Elige una Categoria";
$l['choose_sub_category'] = "Elige una sub-categoría";	
$l['Description'] = "Descripción";
$l['Location'] = "Lugar";
$l['optional'] = "Opcional";
$l['Max2mb'] = "Maximo 2MB por Archivo";
$l['VideoCode'] = "Codigo HTML desde YouTube o algun otro sitio para compartir Videos";
$l['SearchResults'] = "Anuncios clasificados para";	
$l['ContactSeller'] = "Contacto del Vendedor";	
$l['AdStatus'] = "Estatus";
$l['Views'] = "Views";
$l['Approved'] = "Aprovado";
$l['Waiting'] = "Esperando";
$l['Payment'] = "Pago";
$l['Upgrade'] = "Actualización"; 
$l['AreYouSure'] = "¿Estas Seguro?"; 	   
$l['Actions'] = "Acciones";
$l['ShareSocial'] = "Compartir";	
$l['Choosepayment'] = "Selecciona un tipo de actualización";
$l['Topcategory'] = "Promoción - Anuncios desplegados en la parte superior de cada pagina de categoria antes de los anuncios no promocionados.";
$l['BoldAd'] = "Negritas - Titulo de anuncio y el precio seran markados en negritas para resaltar.";
$l['paypalPay'] = "Pago con PayPal";
$l['PaymentThanks'] = "Gracias por su pago.";
$l['PaymentIncomplete'] = "Su pago no se ha completado.";
$l['urlText']   = "URL 'name'";
$l['urlTextEx'] = "(ex. Click here for more information)";
$l['urlLink']   = "URL";
$l['urlLinkEx'] = "(ex. http://www.domain-name.com/link-to-go-to)";
// search
$l['Advancedsearch'] = "Busqueda Avanzada";
$l['From'] = "De";
$l['USAstate'] = "Estado o Región";
$l['Search'] = "Buscar";
// Main menu
$l['home'] = "Inicio";
$l['contact'] = "Contacto";
$l['postAd'] = "Subir Anuncio";
$l['sign_up'] = "Registrarse";
$l['profile'] = "Perfil";
$l['myAds'] = "Mis Anuncios";
$l['messages'] = "Messages";
$l['newmessages'] = "New Messages";
$l['help'] = "Ayuda";
$l['news'] = "Noticias";
$l['articles'] = "Artículos";
// log in
$l['Incorrect_login_or_password'] = "Contraseña o usuario incorrecto";
$l['Login'] = "Usuario";
$l['Password'] = "Contraseña";
$l['Name'] = "Nombre";
$l['YourName'] = "Tu Nombre";
$l['Last_name'] = "Apellido";
$l['Password'] = "Contraseña";
$l['Confirm_password'] = "Confirma contraseña";
$l['Country'] = "País";
$l['City'] = "Ciudad";
$l['Submit'] = "Enviar";
$l['RegComplete'] = "Registrato completo, Ahora puedes";
$l['RegCompletePostAd'] = "subir un articulo clasificado.";
$l['Region'] = "Región";
$l['state'] = "Estado";
$l['Area'] = "Región";
$l['FullAdress'] = "Dirección Completa";
$l['streetAddress'] = "Calle";
$l['Street'] = "Calle";
$l['HouseNum'] = "Número";
$l['Zip'] = "Código Postal";
$l['Address'] = "Dirección";
$l['URL'] = "URL (Sitio Web)";
$l['Fax'] = "Fax";
$l['Mob'] = "Celular";
$l['phone'] = "Teléfono";
$l['mob'] = "Celular";
$l['Profile'] = "Perfil";
$l['EditProfile'] = "Editar perfil";
$l['PassNotEqual'] = "La contraseña no es igual";
$l['LoginNic'] = "Usuario (para acceder y ser mostrado en tus anuncios)";
$l['SubmitReg'] = "Registrarse";
//profile
$l['Delete'] = "Borrar";
$l['Edit'] = "Editar";
$l['AreYouSure'] = "¿Estas Seguro?";
$l['Profile'] = "Perfil";
$l['IncorrOldPass'] = "La contraseña original no es valida";
$l['PassnotEq'] = "Las contraseñas no son iguales";
$l['oldpass'] = "Contraseña Anterior";
$l['newpass'] = "Contraseña nueva";
$l['Back'] = "Atras";
$l['Pages'] = "Paginas";
$l['AllRFields'] = "Todos los campos son obligatorios";
$l['ReqEmail'] = "Escribe tu correo electronico";
$l['EmailInc'] = "Correo electronico incorrecto";
$l['EmailNotFound'] = "Correo electronico no encontrado";
$l['ForgotEmailBody'] = "Tu nueva contraseña";
$l['ForPassword'] = "Recuperación de contraseña";
$l['NewPassSent'] = "Una nueva contraseña fue enviada a tu correo electronico";
// profile
$l['Inbox'] = "Buzón";
$l['Outbox'] = "Buzón de Salida";
$l['Compose'] = "Componer";
$l['Reply'] = "Responder";
$l['DeleteMess'] = "Borrar";
$l['MarkedMessages'] = "Con mensajes seleccionados";
$l['MasrkAsRead'] = "Marcar como leido";
$l['MEssageSecSend'] = "El mensaje ha sido enviado exitosamente";
$l['UserNotFound'] = "Usuario no encontrado";
$l['ForUser'] = "Para";
$l['EnterLogin'] = "Ingresa el usuario";
$l['IncorrectLoginOrPass'] = "Usuario o contraseña incorrecta";
$l['UserNotFound'] = "Usuario no encontrado";
$l['PassNotEqual'] = "La contraseña no es igual";
$l['BothPassReq'] = "Ingresa la contraseña anterior y nueva";
$l['IncOldPass'] = "Contraseña anterior invalida";
$l['ShowOnly'] = "Muestra anuncios solo de mi ciudad";
//PostAd
$l['toPostad'] = "Subir un anuncio.";	
$l['Video'] = "Video";
$l['VideoCode'] = "Ingresa el codigo para incrustar video";
$l['optional'] = "Opcional";
$l['delete'] = "borrar";
$l['images_extensions'] = "Imagenes: (.jpg, .png, .gif - max 2Mb por archivo)";
$l['photos_videos'] = "Fotos y Videos:";
$l['zip_postal_code'] = "Codigo Postal (opcional)";
$l['or'] = "o";
$l['city'] = "Ciudad";
$l['optional'] = "opcional";
$l['us_state'] = "Estado o Región";
$l['country'] = "País";
$l['location'] = "Lugar";
$l['free'] = "Gratis";
$l['best_offer'] = "Mejor Oferta";
$l['wanted'] = "Wanted";
$l['description'] = "Descripción";
$l['title'] = "Titulo";
$l['choose_category'] = "Elegir Categoria";
$l['Price_classified'] = "Precio";
$l['Details'] = "Detalles";
$l['emailAddress'] = "Correo Electronico";
$l['footerLink'] = "Software para anuncios clasificados";
// contacts
$l['ContactName'] = "Su Nombre";
$l['ContactEmail'] = "Su dirección de Correo Electronico";
$l['subject'] = "Sujeto";
$l['message'] = "Mensaje";
$l['SendMessage'] = "Enviar Mensaje";
$l['succSent'] = "Su mensaje ha sido enviado";
$l['captcha_error'] = "PorFavor ingrese el codigo correcto de Captcha";
//Language variable for Email
$e['contact_seller'] = "Contacto Vendedor";
$e['message_sent'] = "Su Mensaje ha sido enviado al vendedor";
$e['invalid_captcha'] = "PorFavor ingrese un codigo Captcha Valido";
$e['firstNameLastName'] = "Nombre y Apellido";
$e['emailAddress'] = "Correo Electronico";
$e['emailMessage'] = "Mensaje";
$e['emailURL'] = "URL";
$e['approvalMailsubject'] = "Se ha subido un nuevo anuncio. Estos son los detalles del anuncio";
$e['approvalMailTitle'] = "Titulo";
$e['approvalMailDescription'] = "Descripción";
$e['approvalMailName'] = "Nombre";
$e['approvalMailPhone'] = "Telefono";
$e['approvalLink'] = "Este es el link de aprobación: (PorFavor ingrese a administración primero) ";
$e['adEditedapprovalMailsubject'] = "Se ha editado un anuncio. Estos son los detalles del anuncio";

//News and Articles
$l['moreInfo'] = "more info >";

// Added to make URLs without odd characters of certain languages	
foreach($l AS $key=>$value)
{
$l[$key] = htmlentities($value); 
}
?>